### ISSUE TITLE
Suggestions for Celestines

### ISSUE THREAD

**Issue by gaforb** [Moffein/EliteReworks#1]
VFX: Instead of the aura being an ugly bubble, it could be a significantly less ugly Area indicator (like warbanner).
On Hit: Slow is boring. I'd recommend taking a page from ZetAspects and have them reduce Armor on hit (you can re-use the full debuff from Shattering Justice).
Alternate On Hit: If you want something a bit more original, they could instead reduce your total damage for a small amount of time.
Aura: instead of invisibility, any non-celestine enemies that die in the aura are revived (as if they had a dio's). This would have to either not affect teleporter bosses, or remove them from the teleporter boss pool when they're defeated the first time (spawning a new one in their place that doesn't count for the teleporter HP bar). It could also simply not affect bosses at all, but I think that'd be losing some of the fun.

**Comment by Moffein** [comment]
I originally had something like that in mind for the Aura (enemies revive as ghosts when killed), but I initially scrapped it due to being visually messy along with being kinda buggy. But I'd be down to give it another shot, and lock it behind a config option for testing.

**Comment by Moffein** [comment]
Forgot to close this, was implemented sometime in November 2021
