### ISSUE TITLE
EliteReworks doesn't scale spawn cost for Adaptive Elites in Augmentum

### ISSUE THREAD

**Issue by BrandonRosa** [Moffein/EliteReworks#10]
This leaves Adaptive Elites the most costly in T1 so they rarely spawn. However in Artifact of Honor, they spawn the MOST.

Would it have to do with mod load order?

**Comment by Moffein** [comment]
Unless Augmentum is also modifying the Vanilla Tier 1 elitedef, there shouldn't be any conflict.
If there is anything that modifies elite cost, keep in mind that it's a shared value that's tied to the EliteTierDef, rather than individual EliteDefs.

**Comment by BrandonRosa** [comment]
My bad. I think Augmentum might "Make" its own seperate tier outside of T1 so it can have its own specific cost multiplier.

I think I copied that bit of code from Aetherium. If there is a fix for Aetherium, it would also work for Augmentum!
If not, I might just add a compatability patch and change the cost multiplier within Augmentum
