### ISSUE TITLE
The T2 minimum stages config is 1 stage off

### ISSUE THREAD

**Issue by Pupo743** [Moffein/EliteReworks#12]
Run.instance.stageClearCount increases every time you leave a non-special stage, so a value of 3 in this setting would mean T2 elites would start spawning after you leave S3 and start S4, however, T2 elites will only start spawning in S5+. I checked this with debugtoolkit's run_set_stages_cleared and director_combat_enable_internal_logs and found out the tier does not become available in S4 at all so it isnt an issue with director credits.

I also tried leaving the value at 2 (which would cause T2 elites to start spawning in S3) and instead it made them available to spawn starting from S4, so that kind of confirms my theory

I believe the exact issue is a missing = in this conditional where it should check for equal or more than instead of simply more than, but I could be wrong as I dont fully understand combat director logic
https://github.com/Moffein/EliteReworks/blob/ab401a3424952506ad45d7cb142fe9ca74135c8e/EliteReworks/Tweaks/ModifyEliteTiers.cs#L144

![imagen](https://github.com/user-attachments/assets/b358fdf2-0554-47c7-bbab-d04e2fe94664)
![imagen](https://github.com/user-attachments/assets/ed7ee047-fc54-4904-862b-1a75a050ea14)
(images taken with a T2 Min Stages value of 2)

**Comment by Moffein** [comment]
Thanks for reporting this, I've fixed the issue.
