### ISSUE TITLE
Overloading Elites are too noisy.

### ISSUE THREAD

**Issue by Lumby** [Moffein/EliteReworks#3]
This isn't exactly a technical breakdown, and I'm no expert on game design so I'm not gonna comment on any of that, but I do have one bit of feedback - the constant explosions from Overloading elites are super noisy, dominating all other game sounds. This is amplified by EliteReworks also generally spawning more elites at once, typically of the same type. A friend got Silence Between Two Strikes on Bandit and it was absolutely deafening.

Thanks for the work you're putting in.

**Comment by Moffein** [comment]
Will take a look at the noise levels, thanks for the feedback.
