### ISSUE TITLE
Any update for Voidtouched Elite?

### ISSUE THREAD

**Issue by motonari728** [Moffein/EliteReworks#4]
Voidtouched Elite is introduced in recent Survivors of the Void DLC.
Is this mod going to update for this elite?

I was killed by Voidtouched's Collapse debuff many times.
I want to tweak damage scale of this debuff.
To deal 400% damage per stack after 3 seconds is too high.
https://riskofrain2.fandom.com/wiki/Status_Effects#Collapse

(I'm learning english)

**Comment by Moffein** [comment]
Yeah, plan is to tweak Voidtouched when the mod updates.
