### ISSUE TITLE
[Suggestion] Volatile & Frenzied elites back?

### ISSUE THREAD

**Issue by DarkD** [Moffein/EliteReworks#7]
Original RoR had elite variants that hadn't made it into RoR2 should be a good idea to bring them back.
Volatile was all about explosions, even had chance to shoot missiles. So they can be about increased damage and pushback in RoR2. Maybe launch said missiles on hit(them being hit).
Frenzied was about speed, teleports and shield bypassing. Seems like that niche isn't taken, so fast attack and general speed, teleports and ignoring shields can be their theme.
Don't know why they didn't made it in RoR2, but surely will give some variance to elites, especially when they started to be actually different with your mod.

**Comment by Moffein** [comment]
I don't plan to add any new elite types to this mod, but the Lost in Transit mod (currently a work in progress) is planning to add them, alongside bringing back Blighted enemies!

**Comment by DarkD** [comment]
Will it be balanced same way as this one or like vanilla? Not much sense to have vanilla balance though... I hope it'll be complimentary for this mod as it proved to be QoL must have one.

**Comment by Moffein** [comment]
From what I know so far, the plan is to use Vanilla stat multipliers, but use EliteReworks multipliers if it is installed.
