### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by zCap80** [Moffein/EliteReworks#8]
Only have one suggestion, a possible setting to allow for T2 elites to spawn earlier than stage 6? For people who don't loop it'd allow them to face the challenges or these T2 elites which I think would be pretty neat. I really like the work you've done so far, keep it up :)

**Comment by Moffein** [comment]
Added!
"T2 Min Stages" setting in the General section of the config. Set to 5 by default (1 loop, 5 stages completed).

**Comment by zCap80** [comment]
well damn, that was quick haha. Thanks again for all you've done!
