### ISSUE TITLE
T2 min stage

### ISSUE THREAD

**Issue by zCap80** [Moffein/EliteReworks#9]
Just a heads up I have the min stage number set to 2 and reduced T2 elite cost to 18 credits and still haven't been seeing any t2 elites, there might be an issue there, not sure if other configuration are running into the same issue

**Comment by Moffein** [comment]
Seems like I made a mistake with the previous version. It was checking loops completed instead of stages completed. Just uploaded a fix, let me know if it works now!

**Comment by zCap80** [comment]
I got around to trying the min stage for T2s out, it seems to possibly be one stage off in the config? i've set it to 2 which means it'd be stage 3 as its min stage i believe? but only have seen T2s starting at stage 4 with that config

**Comment by Moffein** [comment]
Thanks for pointing this out. Found the bug and uploaded a fix.
